[package]
name = "matrix_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflection = { path = "./reflection"}
reflection_macro_attribute = { path = "./reflection_macro_attribute"}
spin_sleep = "1.1.1"

