[package]
name = "matrix_engine"
version = "0.1.0"
edition = "2021"


[dependencies]
lazy_static = "1.4.0"
spin_sleep = "1.1.1"
tokio = { version = "*", features = ["sync"] }
wgpu = "0.17.1"
winit = "0.28.3"
log = { version = "0.4.20", features = ["std"] }
