[package]
name = "matrix_engine"
version = "0.1.0"
edition = "2021"


[dependencies]
num_cpus = "1.16.0"
paste = "1.0.15"
scoped_threadpool = "0.1.9"
tokio = { version = "1", features = ["rt"] }
wgpu = "22.1.0"
winit = "0.30.5"

[[example]]
name = "run"
[[example]]
name = "multithreaded"
